<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Recall.Ollama\Recall.Ollama.csproj" />
    <ProjectReference Include="..\Recall.Storage\Recall.Storage.csproj" />
  </ItemGroup>

</Project>
